### ISSUE TITLE
Missing output from hydra,tigra,breakseq,delly and cnmops

### ISSUE THREAD

**Issue by arumds** [timothyjamesbecker/SVE#13]
Hi,

I have been testing the SVE on dog genome with the below singularity command:

`singularity_wrapper exec tjbsve.sif /software/SVE/scripts/variant_processor.py -v -r ROSY.fa -c chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chr23,chr24,chr25,chr26,chr27,chr28,chr29,chr30,chr31,chr32,chr33,chr34,chr35,chr36,chr37,chr38 -b H027.bam -o svtest -s breakdancer,gatk_haplo,delly,lumpy,cnvnator,hydra,tigra,cnmops,breakseq`

The input BAM file is produced from bwa-mem2. The SVE command has run for 48hrs on 30X genome and timed-out. **The log file is empty**. Here is the output file structure in the output directory:

`   svtest/		    svtestH027_S13.vcf  svtestH027_S3.cov	svtestH027_S3.header.rg  svtestH027_S3.valid	svtestH027_S4.vcf    svtestH027_S9.vcf   svtestH027_S10.vcf  svtestH027_S18.vcf  svtestH027_S3.header	svtestH027_S3.summary	  svtestH027_S4.calls	svtestH027_S9.RData  svtestbd_confg.txt`

Here, there is no VCF file for S3 and the *_S3.cov has coverage info only for chr1-22. Does it somehow looks for only human chromosomes?

And empty VCF file for S9.  Inaddition, svtest/ directory is like below:

**svtest** $ ls *
S11:
del.vcf  dup.vcf  ins.vcf  inv.vcf  tra.vcf

S17:
all-sv.calls.bkpts  bam.stub  bam.stub.config

S35:

 It looks like there are other issues than the time limit as some callers has not given the output VCF. Could you help us to fix and get the output from S3,S9,S11,S17,S35. from the callers hydra,tigra,breakseq,delly and cnmops?

**Comment by timothyjamesbecker** [comment]
Hello, I am not familiar with the dog genome or the ROSY.fa reference fasta, but have used the callers in the SVE many times.  First an foremost to speed up your analysis call individual stages, some of these callers (DEllY, GATK) can take 12+ hours per 50X human genome that is a BAM file of size 180GB:

"singularity_wrapper exec tjbsve.sif /software/SVE/scripts/variant_processor.py -v -r ROSY.fa -c chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chr23,chr24,chr25,chr26,chr27,chr28,chr29,chr30,chr31,chr32,chr33,chr34,chr35,chr36,chr37,chr38 -b H027.bam -o svtest -s breakdancer"

You can alos speed up analysis again by calling each sequence (in || ideally):

"singularity_wrapper exec tjbsve.sif /software/SVE/scripts/variant_processor.py -v -r ROSY.fa -c chr1 -b H027.bam -o svtest -s breakdancer"

More importantly for a good analysis result it that some callers are designed for human and need a good deal of meta-data as input.  If you read the BreakSeq2 paper it uses a breakpoint library which is built from the genome and example variants.  This one is only for human unless the user wants to build a breakpoint library on their own (advanced).  

This is just one example of reference fasta files and masks that need to be prepared for the callers that are in the SVE to work.  You will need to run the prepare_reference.py script which can help to generate many of these files if you have a suitable reference fasta on hand (which I assume you do).

Please fee free to follow up via email since this is not an issue with the SVE since it is functioning as intended, but an issue with how to use it on a dog genome with some of the underlying callers.
