### ISSUE TITLE
Cannot open reference file

### ISSUE THREAD

**Issue by lh12565** [timothyjamesbecker/SVE#5]
Hi, I know little about docker. When I download  SVE and call SV, the following error occurs：

ERROR: Cannot open reference file: /data1/luohao/software/sve/P1-1/Homo_sapiens_assembly38.fasta

I wonder if I need to copy input files to containers, or is there any other way to solve it? I have many samples，and copying too big data is not what I want.

Thanks!
Luo Hao

**Comment by timothyjamesbecker** [comment]
When you are using docker you want to map or attach your hard drive so that the container can read and write your data:

docker -v /path_to_data:/data -it docker_container_name program_name

In my example the folder at /path_to_data/ will show up inside the container as the folder named /data
and you would use the commandline arguments to /data

Does that make sense?

In your case you most likely never set up your data1 folder using the -v argument.  If you can provide your full commandline, I can help you to rewrite the portions that are attaching to your data1 directory
